### ISSUE TITLE
For model code files

### ISSUE THREAD

**Issue by denghuowj** [miccaiif/LNMNet#1]
It's an honor to see the code you shared. But I can't find the code file of your model. Can you tell me which file it is in? If it is not uploaded, can you share it?

**Comment by miccaiif** [comment]
> It's an honor to see the code you shared. But I can't find the code file of your model. Can you tell me which file it is in? If it is not uploaded, can you share it?

Thank you for raising this question. Due to our oversight, we did not notice this issue. We have now added the model file.
